# installJuice.py
import os

ans = input('''
JuiceFileManager Installer
#################################

welcome to the juice file manager installer!
this will download all the required assets for
JFM.

Proceed? (y/n) #: ''')

if ans == 'y':
    os.system("sudo apt update")
    os.system("sudo apt -y install xterm")
    ans = input('''
JuiceFileManager Installer
#################################

Where Would You Like To Install
To?

1. Downloads Folder (~/Downloads)

2. Root Of Filesystem (/)

3. Root User Folder (/root) (For Always Root Users)

4. Home Folder (~/)

#: ''')
    # Downloads The Assets For JFM In The Dir (~/Downloads)
    if ans == '1':
        os.system("mkdir ~/Downloads/JFM")
        print('[<->               ]')
        os.system("mkdir ~/Downloads/JFM/Assets")
        print('[ <->              ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Add.py -q -P ~/Downloads/JFM/Assets")
        print('[  <->             ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Check.py -q -P ~/Downloads/JFM/Assets")
        print('[   <->            ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Copy.py -q -P ~/Downloads/JFM/Assets")
        print('[    <->           ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Delete.py -q -P ~/Downloads/JFM/Assets")
        print('[     <->          ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/DirList.py -q -P ~/Downloads/JFM/Assets")
        print('[      <->         ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Extra.py -q -P ~/Downloads/JFM/Assets")
        print('[       <->        ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Information.py -q -P ~/Downloads/JFM/Assets")
        print('[        <->       ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/MakeDir.py -q -P ~/Downloads/JFM/Assets")
        print('[         <->      ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Move.py -q -P ~/Downloads/JFM/Assets")
        print('[          <->     ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenFile.py -q -P ~/Downloads/JFM/Assets")
        print('[           <->    ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenWeb.py -q -P ~/Downloads/JFM/Assets")
        print('[            <->   ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Read.py -q -P ~/Downloads/JFM/Assets")
        print('[             <->  ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/RemoveDir.py -q -P ~/Downloads/JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Update.py -q -P ~/Downloads/JFM/Assets")
        print('[               <->]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Write.py -q -P ~/Downloads/JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/juicefilemanager4.0-1.py -q -O ~/Downloads/juicefilemanager4.0.py")
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/ShowReadme.py -q -P ~/Downloads/JFM/Assets")

    # Downloads The Assets For JFM In The Dir (/)
    if ans == '2':
        os.system("mkdir /JFM")
        print('[<->               ]')
        os.system("mkdir /JFM/Assets")
        print('[ <->              ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Add.py -q -P /JFM/Assets")
        print('[  <->             ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Check.py -q -P /JFM/Assets")
        print('[   <->            ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Copy.py -q -P /JFM/Assets")
        print('[    <->           ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Delete.py -q -P /JFM/Assets")
        print('[     <->          ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/DirList.py -q -P /JFM/Assets")
        print('[      <->         ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Extra.py -q -P ~/JFM/Assets")
        print('[       <->        ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Information.py -q -P /JFM/Assets")
        print('[        <->       ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/MakeDir.py -q -P /JFM/Assets")
        print('[         <->      ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Move.py -q -P /JFM/Assets")
        print('[          <->     ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenFile.py -q -P /JFM/Assets")
        print('[           <->    ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenWeb.py -q -P /JFM/Assets")
        print('[            <->   ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Read.py -q -P /JFM/Assets")
        print('[             <->  ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/RemoveDir.py -q -P /JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Update.py -q -P /JFM/Assets")
        print('[               <->]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Write.py -q -P /JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/juicefilemanager4.0-2.py -q -O /juicefilemanager4.0.py")
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/ShowReadme.py -q -P /JFM/Assets")
    # Downloads The Assets For JFM In The Dir (/root)
    if ans == '3':
        os.system("mkdir /root/JFM")
        print('[<->               ]')
        os.system("mkdir /root/JFM/Assets")
        print('[ <->              ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Add.py -q -P /root/JFM/Assets")
        print('[  <->             ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Check.py -q -P /root/JFM/Assets")
        print('[   <->            ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Copy.py -q -P /root/JFM/Assets")
        print('[    <->           ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Delete.py -q -P /root/JFM/Assets")
        print('[     <->          ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/DirList.py -q -P /root/JFM/Assets")
        print('[      <->         ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Extra.py -q -P /root/JFM/Assets")
        print('[       <->        ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Information.py -q -P /root/JFM/Assets")
        print('[        <->       ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/MakeDir.py -q -P /root/JFM/Assets")
        print('[         <->      ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Move.py -q -P /root/JFM/Assets")
        print('[          <->     ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenFile.py -q -P /root/JFM/Assets")
        print('[           <->    ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenWeb.py -q -P /root/JFM/Assets")
        print('[            <->   ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Read.py -q -P /root/JFM/Assets")
        print('[             <->  ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/RemoveDir.py -q -P /root/JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Update.py -q -P /root/JFM/Assets")
        print('[               <->]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Write.py -q -P /root/JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/juicefilemanager4.0-3.py -q -O /root/juicefilemanager4.0.py")
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/ShowReadme.py -q -P /root/JFM/Assets")

    # Downloads The Assets For JFM In The Dir (~/)
    if ans == '4':
        os.system("mkdir ~/JFM")
        print('[<->               ]')
        os.system("mkdir ~/JFM/Assets")
        print('[ <->              ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Add.py -q -P ~/JFM/Assets")
        print('[  <->             ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Check.py -q -P ~/JFM/Assets")
        print('[   <->            ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Copy.py -q -P ~/JFM/Assets")
        print('[    <->           ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Delete.py -q -P ~/JFM/Assets")
        print('[     <->          ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/DirList.py -q -P ~/JFM/Assets")
        print('[      <->         ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Extra.py -q -P ~/JFM/Assets")
        print('[       <->        ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Information.py -q -P ~/JFM/Assets")
        print('[        <->       ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/MakeDir.py -q -P ~/JFM/Assets")
        print('[         <->      ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Move.py -q -P ~/JFM/Assets")
        print('[          <->     ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenFile.py -q -P ~/JFM/Assets")
        print('[           <->    ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/OpenWeb.py -q -P ~/JFM/Assets")
        print('[            <->   ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Read.py -q -P ~/JFM/Assets")
        print('[             <->  ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/RemoveDir.py -q -P ~/JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Update.py -q -P ~/JFM/Assets")
        print('[               <->]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/Write.py -q -P ~/JFM/Assets")
        print('[              <-> ]')
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/juicefilemanager4.0-4.py -q -O ~/juicefilemanager4.0.py")
        os.system("wget https://raw.githubusercontent.com/EnderNightLord-ChromeBook/JuiceFileManagerMinimal/master/assets/ShowReadme.py -q -P ~/JFM/Assets")
